### ISSUE TITLE
Ansible fails on a warning message coming from `brew` for a Formula which has an identically named Cask

### ISSUE THREAD

**Issue by ringods** [geerlingguy/ansible-collection-mac#104]
For my setup, I have `httpie` and `volta` in my list of `homebrew_installed_packages`. These formulae have an identical named cask (which I'm not using).

I was making an update to my setup and ran `ansible`, but I'm now bumping into an issue where it seems to fail on a generated warning message:

```
failed: [myhost] (item=httpie) => {"ansible_loop_var": "item", "changed": false, "item": "httpie", "msg": "Warning: Treating httpie as a formula. For the cask, use homebrew/cask/httpie or specify the `--cask` flag."}
```

This makes my `ansible` run to end half way.

**Comment by ashtl** [comment]
Hey @ringods - I've been having the same issue with the xcodes formula. This isn't an issue with @geerlingguy collection. Seems to be a change that introduced this behavior so if you go back to an older version it works fine. 
`ansible-galaxy collection install community.general:==8.4.0`

You can read more [here](https://github.com/ansible-collections/community.general/issues/8274)

**Comment by ringods** [comment]
@ashtl thanks for linking the other issue. I will revert to 8.4.0, but will keep an eye when 9.0.0 is released.

https://github.com/ansible-collections/community.general/pull/8275/files#diff-109efc689f4332320bad76472328471ef85a0faeae32ec97086c9790e244c69eR85
