### ISSUE TITLE
mas no longer supports logging in

### ISSUE THREAD

**Issue by toby-griffiths** [geerlingguy/ansible-collection-mac#11]
It looks like the `mas` app no longer supports logging in (after I spent ages trying to debug getting the credential conditions in ansible to work! 😭)

Can you imagine a valid reason for these to be kept in the playbook now this is the case?  If not, I can submit a PR to remove them.

**Comment by geerlingguy** [comment]
I forget which macOS versions it was working in, but if any are still actively supported by Apple, I wouldn't just pull the feature unless it definitely won't work on the older OSes too.

**Comment by toby-griffiths** [comment]
Ah.  Good point.  There's an [open issue on the mas repo](https://github.com/mas-cli/mas/issues/164).

Since this dues report, in the task output, that login is disabled, and a link to the issue, I'll close this issue.  Hopefully it will be fixable upstream.
