### ISSUE TITLE
Role `geerlingguy.mac.homebrew` hangs on Monterrey

### ISSUE THREAD

**Issue by alonsodomin** [geerlingguy/ansible-collection-mac#30]
Just updated from the deprecated `geerlingguy.homebrew` Ansible role and when trying to run my playbook, Ansible hangs at this step:

```
TASK [geerlingguy.mac.homebrew : Ensure Homebrew parent directory has correct permissions (MacOS >= 10.13).] ***********************************************************************************************
```

My Hombrew directory is at `/usr/local/Homebrew`, so it's prefix (`homebrew_prefix`) should be `/usr/local`. I checked myself that the parent directory does have the correct ownership, but can't figure out why it hangs at that point, like if it was expecting some user input at that point.

My Ansible version is `2.12.1`.

**Comment by webflo** [comment]
Please verify your SSH connection settings. Take a look at https://github.com/geerlingguy/mac-dev-playbook/issues/93 for more information.

**Comment by goatsweater** [comment]
I can into the same problem. Ansible `2.12.4`, running on a local Mac.

As indicated above, adding `ANSIBLE_SSH_PIPELINING=0` in front of the command does help.
