### ISSUE TITLE
mas does not work in OSX 10.13+

### ISSUE THREAD

**Issue by dspolleke** [geerlingguy/ansible-collection-mac#33]
As menstioned in [https://github.com/mas-cli/mas/issues/164](url) the login does not work in modern OSX versions. 

this results in very strange errors. 

running mas install on the CLI if logged in, however, if you let the role install it errors out. 
a solution may be to NOT try to log in in versions >10.13 and just try to login. 

the problem with that is that you need to identify the os version. 

when i run ansible -m setup on my mac it gives me this relevant information: 

        "ansible_os_family": "Darwin",
        "ansible_osrevision": "199506",
        "ansible_osversion": "21A559",

maybe the kernel version would be  a clue
      "ansible_kernel_version": "Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101",

I may be able to help solve this, but i do not have the information to do so.

**Comment by geerlingguy** [comment]
After setting up a brand new Mac Studio today, everything installed correctly, and I didn't require any modifications on 12.3.

Could it be an issue with 10.x only?

**Comment by geerlingguy** [comment]
I also tried this on a brand new M2 MacBook Air today, and had no issues. You have to make sure you're signed in prior to running the role, maybe there was a signin issue? Closing unless there's any further info.
