### ISSUE TITLE
dockutil < 3.0 does not work on monterey

### ISSUE THREAD

**Issue by olekristensen** [geerlingguy/ansible-collection-mac#42]
Hi there,

Dockutil < 3.0 uses python2 that has been removed from macOS.

Dockutil > 3.0 solves this by reimplementing in swift, but this results in a binary distribution format.

Brew will not accept prebuilt binaries as other than casks. This issue is described here:
https://github.com/kcrawford/dockutil/issues/127

The workaround is given in the thread, tap your own recipe that installs binary instead.

To make this work with your ansible-collection it would be great to make the dockutil install optional - or - to allow a variable for a tap.

**Comment by lotyp** [comment]
Currently writing provisioning playbook and also will use dockutil, that's why i've created that tap. Need to take a look at this one, or probably I will have to re-implement role by myself to work with my tap.

**Comment by olekristensen** [comment]
@lotyp if you do it with a fork of this repo and provide a pr 🥳

**Comment by geerlingguy** [comment]
@olekristensen - I'd be amenable to making the dockutil install portion optional. I'm hoping it'll be able to be automated without a custom tap soon, so I wouldn't have to add some messy code to set that up myself, though. Annoying to maintain that in the role.

**Comment by olekristensen** [comment]
@geerlingguy yep, optional install sounds like the least complex solution until the brew cask appears…

**Comment by lotyp** [comment]
> @lotyp if you do it with a fork of this repo and provide a pr 🥳

@olekristensen 

https://github.com/wayofdev/ansible-role-dock

Here you go. I made this role, as I'm working on a bigger, open source project and I needed dock role. Currently geergling's role wont work with dockutil 3.x and Monterey.

So I did development from zero.

Also role solves problem with this PR: https://github.com/geerlingguy/ansible-collection-mac/pull/26

No more restarts after each, newly added, dockitem 🎉

**Comment by Rooster212** [comment]
Took me a while to find this thread and the fix... but I found it eventually, after fixing it on my machine. I actually ended up using the workaround mentioned in this thread (someone created a binary cask and I just installed that, that fixed it for me): https://github.com/kcrawford/dockutil/issues/127

**Comment by geerlingguy** [comment]
Merged the 'make install optional', and I've also defaulted to installing `hpedrorodrigues/tools/dockutil` (and making the cask name optional, in case you want to set one of your own).
