### ISSUE TITLE
Question | Would `mac.homebrew` role work on Linux?

### ISSUE THREAD

**Issue by Mattszczp** [geerlingguy/ansible-collection-mac#44]
I recently found out that Homebrew can be installed on Linux. I was wondering if the homebrew role would work on it.

**Comment by geerlingguy** [comment]
In this collection, no—I don't have plans for making the homebrew role work under Linux.

**Comment by mi-skam** [comment]
Good to know your intensions @geerlingguy , I think one needs to separate the role from the collection and dumb down some of its capabilities, as not all features have been ported to Linux (yet), e.G. homebrews casks.
