### ISSUE TITLE
Workaround to overcome the homebrew role failing because of PATH

### ISSUE THREAD

**Issue by juan-vg** [geerlingguy/ansible-collection-mac#49]
## Intro

It's still unclear to me, but this error seems to happen on ARM-based macOS

## What you could get

When using the homebrew role in a playbook as follows

```yaml
roles:
  - elliotweiser.osx-command-line-tools
  - geerlingguy.mac.homebrew
```
you could get errors like `Failed to find required executable brew in paths`

```bash
TASK [homebrew : Ensure configured taps are tapped.] ***************************
failed: [default] (item=homebrew/core) => {"ansible_loop_var": "item", "changed": false, "item": "homebrew/core", "msg": "Failed to find required executable brew in paths: /opt/homebrew/Homebrew:/usr/bin:/bin:/usr/sbin:/sbin"}
failed: [default] (item=homebrew/cask) => {"ansible_loop_var": "item", "changed": false, "item": "homebrew/cask", "msg": "Failed to find required executable brew in paths: /opt/homebrew/Homebrew:/usr/bin:/bin:/usr/sbin:/sbin"}
failed: [default] (item=adoptopenjdk/openjdk) => {"ansible_loop_var": "item", "changed": false, "item": "adoptopenjdk/openjdk", "msg": "Failed to find required executable brew in paths: /opt/homebrew/Homebrew:/usr/bin:/bin:/usr/sbin:/sbin"}
```

## How to solve it

```yaml
tasks:
  - name: Install HomeBrew
    include_role:
      name: geerlingguy.mac.homebrew
      apply:
        environment:
          PATH: '{{homebrew_install_path}}/bin:{{ ansible_env.PATH }}'
```

**Comment by KriegersBlog** [comment]
I came across the same error in issue #47 and i also did the same thing. After that i used an export command in the .zshrc to not longer have to deal with this in the playbooks.

**Comment by geerlingguy** [comment]
Note that what I currently do is add this to my instructions:

https://github.com/geerlingguy/mac-dev-playbook#installation

> Run the following command to add Python 3 to your $PATH: `export PATH="$HOME/Library/Python/3.8/bin:/opt/homebrew/bin:$PATH"`

And in my dotfiles, I have this line: https://github.com/geerlingguy/dotfiles/blob/master/.zshrc#L22

**Comment by dspolleke** [comment]
I would prefer an automation step in stead of an instruction.

**Comment by geerlingguy** [comment]
Something like that could work — I've traditionally just updated the path by hand, but if someone were willing to make a PR I would be willing to merge.

**Comment by dspolleke** [comment]
Would this be something we fix in the collection / role. but i do not see how i can include this in the tasks/main.yml file or where it should be implemented. 
We could fix it in the mac-dev-playbook.  i would prefer to fix it here...
