### ISSUE TITLE
Lost dependency on elliotweiser.osx-command-line-tools

### ISSUE THREAD

**Issue by jdumas** [geerlingguy/ansible-collection-mac#5]
Hi there. It seems that your role `geerlingguy.mac.homebrew` doesn't include the dependency on `elliotweiser.osx-command-line-tools`, which was present in `geerlingguy.homebrew`. Should it be added back?

**Comment by geerlingguy** [comment]
Unfortunately, it's impossible for Collection roles to depend on roles that are not in part of a collection. I hate it, but that's apparently "the way things are" in Ansible now :(

See issue I just opened: https://github.com/ansible/ansible/issues/74979

Maybe we can get this changed.
