### ISSUE TITLE
Support --allhomes for dockutil

### ISSUE THREAD

**Issue by strifel** [geerlingguy/ansible-collection-mac#59]
Managing a device with multiple user using the ansible dock role is complicated
due to the role not supporting the --allhomes or the dock-plist.

It would be great supporting either of the options.
A problem with that is that this would require the role potentially needing
to become root.

Getting the dock position would probably be a lot more complicated, too.
Maybe it would be easier just passing the plist location and a user potentially running/including
the role multiple times.

Thanks for all the hard work you put into all your roles!

**Comment by strifel** [comment]
For people in the future stumbling upon this issue:
I did workaround this issue not using the role, but just creating the dock and copying
the plist to every user.
Its far from perfect, but works for me at the moment.

**Comment by geerlingguy** [comment]
As long as the feature wouldn't _require_ root (e.g. if someone didn't specify the option), I'd be okay with accepting a PR that doesn't break the existing default one-use use case. It seems niche enough though (most users sharing a Mac would probably have different apps/dock layouts), that I'd rather not add too much complexity here.
