### ISSUE TITLE
`ansible.builtin.package` not working after homebrew role

### ISSUE THREAD

**Issue by pavelzw** [geerlingguy/ansible-collection-mac#61]
When installing homebrew with `geerlingguy.mac.homebrew` and trying to install packages directly afterwards using `ansible.builtin.package`, this fails with the following error message:

```
The full traceback is:
NoneType: None
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "msg": "Could not find a module for unknown."
}
```

This is because `ansible_pkg_mgr` is set to `unknown` when first loading the playbook. This is then [loaded](https://cs.github.com/ansible/ansible/blob/5ac40b358d7d64e4169813e400c19f869b17183c/lib/ansible/plugins/action/package.py#L51) in `ansible.builtin.package`. After the installation, the facts are not recollected.

**Comment by geerlingguy** [comment]
Merged into a new 2.1.0 release, thanks!
