### ISSUE TITLE
Failed geerlingguy.mac.homebrew : Ensure proper ownership on homebrew_install_path subdirs.

### ISSUE THREAD

**Issue by nalabjp** [geerlingguy/ansible-collection-mac#78]
When I run homebrew role in my environment, it fails with the following error.
![image](https://user-images.githubusercontent.com/1544172/236880404-3cf4fc6f-881f-40b6-a299-470dac4ba9e0.png)
I have no idea why, but it should have worked fine when I was using OSX12.

Commenting out the following line seems to work correctly, so I am working around it for now .
https://github.com/geerlingguy/ansible-collection-mac/blob/2.1.1/roles/homebrew/tasks/main.yml#L73

My environments
ansible-collection-mac: 2.1.1
OSX: 13.3.1
ansible: 2.13.5
python: 3.10.10

**Comment by excalq** [comment]
This error occurred for me with applications that I had manually installed, but added after the fact to the `homebrew_cask_apps` config list. Renaming temporarily them in `/Applicaitons` worked around the issue, but I should reinstall them directly through Ansible+Homebrew.
