### ISSUE TITLE
Homebrew fails when tapping homebrew/core

### ISSUE THREAD

**Issue by andreasbrgmn** [geerlingguy/ansible-collection-mac#85]
It seems Homebrew has recently switched behavior when user taps the default cask `homebrew/core` ([PR](https://github.com/Homebrew/brew/pull/16306)|[commit](https://github.com/Homebrew/brew/blame/f61ef4be2f0c622ceb1c31b7e12969bf01762447/Library/Homebrew/tap.rb#L76)). Instead of warning user, it now fails the process, which ultimately causes the step `Ensure configured taps are tapped` ([link](https://github.com/geerlingguy/ansible-collection-mac/blob/028a5f1fa94ac2ac35a9fb0065123cdbe3883550/roles/homebrew/tasks/main.yml#L121)) to fail since `homebrew/core` is the [default value](https://github.com/geerlingguy/ansible-collection-mac/blob/028a5f1fa94ac2ac35a9fb0065123cdbe3883550/roles/homebrew/defaults/main.yml#L15) of `homebrew_taps`.

**Ex. output:** 
```shell
TASK [geerlingguy.mac.homebrew : Ensure configured taps are tapped.] **************************************************************************************************************************************
failed: [Node-1] (item=homebrew/core) => changed=false 
  ansible_loop_var: item
  item: homebrew/core
  msg: |-
    added: 0, unchanged: 0, error: failed to tap: homebrew/core due to Error: Tapping homebrew/core is no longer typically necessary.
    Add --force if you are sure you need it done.
```

**Comment by kalabiyau** [comment]
as a temp workaround we override homebrew_taps like here:

```
homebrew_taps: []
```

when required we feed explicit taps to as vars to a task

**Comment by Guray00** [comment]
Sorry for the dumb question, where should we put that line?

**Comment by kalabiyau** [comment]
No such thing as a dumb question @Guray00 ;) we put into our top-level inventory group_var aka `all.yml`.  Some examples you can find [here](https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html)

**Comment by andreasbrgmn** [comment]
> as a temp workaround we override homebrew_taps like here:
> 
> ```
> homebrew_taps: []
> ```
> 
> when required we feed explicit taps to as vars to a task

Ah sweet, thanks @kalabiyau

**Comment by nqui** [comment]
> as a temp workaround we override homebrew_taps like here:
> 
> ```
> homebrew_taps: []
> ```
> 
> when required we feed explicit taps as vars to a task

Hi @kalabiyau, are you running this on an apple silicon mac? On an intel mac, this override doesn't work. I've added a debug task to print the value of `homebrew_taps`. Even with `homebrew_taps: []` set in `defaults/main.yml`:
```
TASK [geerlingguy.mac.homebrew : print homebrew_taps] *********************************
ok: [127.0.0.1] => 
  msg:
  - homebrew/core
  - homebrew/cask

TASK [geerlingguy.mac.homebrew : Ensure configured taps are tapped.] ******************
failed: [127.0.0.1] (item=homebrew/core) => changed=false 
  ansible_loop_var: item
  item: homebrew/core
  msg: |-
    added: 0, unchanged: 0, error: failed to tap: homebrew/core due to Error: Tapping homebrew/core is no longer typically necessary.
    Add --force if you are sure you need it done.
failed: [127.0.0.1] (item=homebrew/cask) => changed=false 
  ansible_loop_var: item
  item: homebrew/cask
  msg: |-
    added: 0, unchanged: 0, error: failed to tap: homebrew/cask due to Error: Tapping homebrew/cask is no longer typically necessary.
    Add --force if you are sure you need it done.
```

**Comment by kalabiyau** [comment]
@nqui we use both and it worked for us on both afaik
