### ISSUE TITLE
Tapping default homebrew taps is broken

### ISSUE THREAD

**Issue by nqui** [geerlingguy/ansible-collection-mac#88]
Even with the change in PR #87 the task `Ensure configured taps are tapped.` still fails due to `homebrew_taps` not being empty. I'm not able to find anywhere that would possibly populate this default variable. It could be that this is some weird behaviour on an intel mac...?

I'm running locally on an intel mac: 
```
Monterey v12.7.2
---
ansible [core 2.15.8]
python version = 3.9.6
jinja version = 3.1.2
```

I've ensured that I've got the most recent collection update that contains the changes from #87 

Validated that `homebrew_taps` definition is empty in `defaults/main.yml`:
`homebrew_taps: []`

Here's the error output. I've added a debug task to print the value of `homebrew_taps`. Somehow it's populated with values:
```
TASK [geerlingguy.mac.homebrew : print homebrew_taps] *********************************
ok: [127.0.0.1] => 
  msg:
  - homebrew/core
  - homebrew/cask

TASK [geerlingguy.mac.homebrew : Ensure configured taps are tapped.] ******************
failed: [127.0.0.1] (item=homebrew/core) => changed=false 
  ansible_loop_var: item
  item: homebrew/core
  msg: |-
    added: 0, unchanged: 0, error: failed to tap: homebrew/core due to Error: Tapping homebrew/core is no longer typically necessary.
    Add --force if you are sure you need it done.
failed: [127.0.0.1] (item=homebrew/cask) => changed=false 
  ansible_loop_var: item
  item: homebrew/cask
  msg: |-
    added: 0, unchanged: 0, error: failed to tap: homebrew/cask due to Error: Tapping homebrew/cask is no longer typically necessary.
    Add --force if you are sure you need it done.
```

I'd love to contribute a fix for this, but I don't have a clue how the `homebrew_taps` variable contains values when it's set to an empty array in `defaults/main.yml`

As a workaround, I've commented out the `Ensure configured taps are tapped.` task.

**Comment by geerlingguy** [comment]
@nqui - Probably coming from the playbook level — in your playbook, do you have a config.yml or default.config.yml that might be setting that variable before the role even runs?

**Comment by nqui** [comment]
> @nqui - Probably coming from the playbook level — in your playbook, do you have a config.yml or default.config.yml that might be setting that variable before the role even runs?

Yup you are correct. I appreciate your help!

![image](https://github.com/geerlingguy/ansible-collection-mac/assets/16074620/1e75fbbc-9d43-46eb-854e-35287ef1cce4)
